### ISSUE TITLE
Remove webview and offer a dialog to directly browse and post issues to github via github API

### ISSUE THREAD

**Issue by sgaist** [qt-pods/qt-pods#24]
Hi,

Since the module is being deprecated in favor QtWebEngine, I was wondering if it makes sense to use it in qt-pods ? 

It looks like it's used only to show users the issue page so why not just provide a link so they can use their favorite browser to come here ?

**Comment by jacob3141** [comment]
You probably noticed I also integrated a simple irc chat client while knowing that there are a whole lot of better clients out there. I know that people like you who are very much into open source will naturally go to github and report issues if you encounter problems, but I was having beginners in mind. I wanted to present them the github issues page right in the app, so they see what they have to do in case something isn't working for them.

After all, I think it's worth adding an option to not show that tab? So that "advanced users" will simply go to gh.

**Comment by jacob3141** [comment]
@samuelgaist What shall we agree on? Does the solution I provided make sense to you?

**Comment by sgaist** [comment]
I see your point. In that case wouldn't it be more simple for a beginner user to get a dialog and use the GitHub api to post issues ?

**Comment by jacob3141** [comment]
Well, this is a quick and already working solution. I support the idea to improve it, so I am going to mark this as a refactoring issue and adjust the title.
